In [97]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

import seaborn as sn

In [98]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

In [99]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Ex_0914_diabetes/diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [100]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

Classifiation 4개

In [101]:
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

In [102]:
X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [103]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((614, 8), (154, 8), (614,), (154,))

In [104]:
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [105]:
pred_dt = model_dt.predict(X_test)
print(classification_report(y_test, pred_dt))

              precision    recall  f1-score   support

           0       0.87      0.82      0.85       107
           1       0.64      0.72      0.68        47

    accuracy                           0.79       154
   macro avg       0.76      0.77      0.76       154
weighted avg       0.80      0.79      0.80       154

In [106]:
model_rf= RandomForestClassifier()
model_rf.fit(X_train, y_train)

RandomForestClassifier()

In [107]:
pred_rf = model_rf.predict(X_test)
print(classification_report(y_test, pred_rf))

              precision    recall  f1-score   support

           0       0.85      0.87      0.86       107
           1       0.69      0.66      0.67        47

    accuracy                           0.81       154
   macro avg       0.77      0.76      0.77       154
weighted avg       0.80      0.81      0.80       154

In [108]:
model_lr = LogisticRegression(max_iter=200)
model_lr.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [109]:
pred_lr = model_lr.predict(X_test)
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.84      0.92      0.88       107
           1       0.76      0.62      0.68        47

    accuracy                           0.82       154
   macro avg       0.80      0.77      0.78       154
weighted avg       0.82      0.82      0.82       154

In [110]:
model_kn = KNeighborsClassifier()
model_kn.fit(X_train, y_train)

KNeighborsClassifier()

In [111]:
pred_kn = model_kn.predict(X_test)
print(classification_report(y_test, pred_kn))

              precision    recall  f1-score   support

           0       0.83      0.81      0.82       107
           1       0.59      0.62      0.60        47

    accuracy                           0.75       154
   macro avg       0.71      0.72      0.71       154
weighted avg       0.76      0.75      0.75       154

Regression 3개

In [112]:
X_reg = df.drop(["BMI", "Outcome"], axis=1)
y_reg = df["BMI"]

In [113]:
from sklearn.model_selection import train_test_split

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size=0.2,
    random_state=0
)

In [114]:
X_train_reg.shape, X_test_reg.shape, y_train_reg.shape, y_test_reg.shape

((614, 7), (154, 7), (614,), (154,))

In [115]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

model_lr_reg = LinearRegression()

model_lr_reg.fit(X_train_reg, y_train_reg)

pred_lr_reg = model_lr_reg.predict(X_test_reg)

print("MSE:", mean_squared_error(y_test_reg, pred_lr_reg))
print("R2:", r2_score(y_test_reg, pred_lr_reg))

MSE: 49.41151592580262
R2: 0.16752164917717072

In [116]:
from sklearn.tree import DecisionTreeRegressor

model_dt_reg = DecisionTreeRegressor()

model_dt_reg.fit(X_train_reg, y_train_reg)

pred_dt_reg = model_dt_reg.predict(X_test_reg)

print("MSE:", mean_squared_error(y_test_reg, pred_dt_reg))
print("R2:", r2_score(y_test_reg, pred_dt_reg))

MSE: 91.45194805194804
R2: -0.5407697065627746

In [117]:
from sklearn.ensemble import RandomForestRegressor

model_rf_reg = RandomForestRegressor()

model_rf_reg.fit(X_train_reg, y_train_reg)

pred_rf_reg = model_rf_reg.predict(X_test_reg)

print("MSE:", mean_squared_error(y_test_reg, pred_rf_reg))
print("R2:", r2_score(y_test_reg, pred_rf_reg))

MSE: 46.55224575324678
R2: 0.21569423553093625

In [118]:
print("Linear Regression")
print("MSE:", mean_squared_error(y_test_reg, pred_lr_reg))
print("R2 :", r2_score(y_test_reg, pred_lr_reg))

print("\nDecision Tree")
print("MSE:", mean_squared_error(y_test_reg, pred_dt_reg))
print("R2 :", r2_score(y_test_reg, pred_dt_reg))

print("\nRandom Forest")
print("MSE:", mean_squared_error(y_test_reg, pred_rf_reg))
print("R2 :", r2_score(y_test_reg, pred_rf_reg))

Linear Regression
MSE: 49.41151592580262
R2 : 0.16752164917717072

Decision Tree
MSE: 91.45194805194804
R2 : -0.5407697065627746

Random Forest
MSE: 46.55224575324678
R2 : 0.21569423553093625